/****************************************************************************
 ** 
 ** This demo file is part of yFiles.NET 5.6.
 ** Copyright (c) 2000-2024 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 ** 
 ** yFiles demo files exhibit yFiles.NET functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 ** 
 ** Owners of a valid software license for a yFiles.NET version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles.NET powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles.NET
 ** license agreement.
 ** 
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ** 
 ***************************************************************************/

using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Windows.Forms;
using Demo.yFiles.Graph.BezierEdgeStyle.Properties;
using yWorks.Controls;
using yWorks.Controls.Input;
using yWorks.Geometry;
using yWorks.Graph;
using yWorks.Graph.LabelModels;
using yWorks.Graph.Styles;
using yWorks.GraphML;

namespace Demo.yFiles.Graph.BezierEdgeStyle
{
  /// <summary>
  /// Simple demo that hosts a <see cref="GraphControl"/>
  /// which enables graph editing via the default <see cref="GraphEditorInputMode"/> 
  /// input mode for editing graphs.
  /// </summary>
  /// <remarks>
  /// This demo also supports grouped graphs. Selected nodes can be grouped 
  /// in so-called group nodes using CTRL-G and again be ungrouped using CTRL-U. 
  /// To move sets of nodes into and out of group nodes using the mouse, hold down 
  /// the SHIFT key while dragging.
  /// <para>
  /// Apart from graph editing, the demo demonstrates various basic features that are already
  /// present on GraphControl (either as predefined commands or as simple method calls),
  /// for example load/save/export.
  /// </para>
  /// <para>
  /// In addition to the GraphControl itself, the demo also shows how to use the GraphOverviewControl.
  /// </para>
  /// </remarks>
  public partial class BezierEdgeStyleForm : Form
  {
    /// <summary>
    /// Automatically generated by Visual Studio.
    /// Wires up the UI components and adds a 
    /// <see cref="GraphControl"/> to the form.
    /// </summary>
    public BezierEdgeStyleForm() {
      SmoothEditing = true;
      bezierEdgeSegmentLabelModel = new BezierEdgeSegmentLabelModel();
      bezierPathLabelModel = new BezierEdgePathLabelModel();
      Angle = 0;
      AutoRotation = true;
      AutoSnapping = true;
      EnableEditing = true;
      InitializeComponent();
      RegisterToolStripCommands();
      RegisterMenuItemCommands();

      description.LoadFile(new MemoryStream(Resources.description), RichTextBoxStreamType.RichText);
    }

    #region Command registration

    private void RegisterToolStripCommands() {
      zoomInButton.SetCommand(Commands.IncreaseZoom, graphControl);
      zoomOutButton.SetCommand(Commands.DecreaseZoom, graphControl);
      fitContentButton.SetCommand(Commands.FitContent, graphControl);

      loadGraphMLButton.SetCommand(Commands.Open, graphControl);
      saveGraphMLButton.SetCommand(Commands.SaveAs, graphControl);
      
      undoButton.SetCommand(Commands.Undo, graphControl);
      redoButton.SetCommand(Commands.Redo, graphControl);

      zoom11ToolStripMenuItem.SetCommand(Commands.Zoom, 1.0d, graphControl);
    }

    private void RegisterMenuItemCommands() {
      zoomInToolStripMenuItem.SetCommand(Commands.IncreaseZoom, graphControl);
      zoomOutToolStripMenuItem.SetCommand(Commands.DecreaseZoom, graphControl);
      fitContentToolStripMenuItem.SetCommand(Commands.FitContent, graphControl);

      openToolStripMenuItem.SetCommand(Commands.Open, graphControl);
      saveToolStripMenuItem.SetCommand(Commands.SaveAs, graphControl);

      cutToolStripMenuItem.SetCommand(Commands.Cut, graphControl);
      copyToolStripMenuItem.SetCommand(Commands.Copy, graphControl);
      pasteToolStripMenuItem.SetCommand(Commands.Paste, graphControl);
      deleteToolStripMenuItem.SetCommand(Commands.Delete, graphControl);
      undoToolStripMenuItem.SetCommand(Commands.Undo, graphControl);
      redoToolStripMenuItem.SetCommand(Commands.Redo, graphControl);
    }

    #endregion

    /// <summary>
    /// Initializes the graph and the input mode.
    /// </summary>
    /// <seealso cref="InitializeGraph"/>
    protected override void OnLoad(EventArgs e) {
      // Set a custom visual creator for the overview so Bezier edges get rendered
      graphOverviewControl.GraphVisualCreator = new BezierOverviewVisualCreator(graphOverviewControl.Graph);

      // initialize the graph
      InitializeGraph();

      SetupGraphML();

      // initialize the input mode
      graphControl.InputMode = CreateEditorMode();
      sampleComboBox.SelectedIndex = 0;
    }

    /// <summary>
    /// Creates the default input mode for the GraphControl, a <see cref="GraphEditorInputMode" />.
    /// </summary>
    /// <returns>a new GraphEditorInputMode instance and configures snapping and orthogonal edge editing</returns>
    protected virtual IInputMode CreateEditorMode() {
      var graphEditorInputMode = new BezierGraphEditorInputMode(this);

      return graphEditorInputMode;
    }
    
    /// <summary>
    /// Initializes the graph instance setting default styles
    /// and creating a small sample graph.
    /// </summary>
    protected virtual void InitializeGraph() {
      Graph.SetUndoEngineEnabled(true);

      //We need to provide our own handles for bezier edge bends:
      RegisterBezierDecorators();

      //Trigger re-evaluation of handles remove stale handles
      Graph.BendRemoved += delegate { RequeryHandles(); };
      Graph.BendAdded += delegate { RequeryHandles(); };

      Graph.NodeDefaults.Style = new ShapeNodeStyle { Brush = Brushes.LightGray, Shape = ShapeNodeShape.Ellipse, Pen = null};
      Graph.EdgeDefaults.Style = bezierEdgeStyle;
      Graph.EdgeDefaults.Labels.Style = new DefaultLabelStyle {
          BackgroundBrush = Brushes.White,
          BackgroundPen = new Pen(new SolidBrush(Color.FromArgb(0xff, 0xa5, 0x00)), 1),
          Insets = new InsetsD(3),
          StringFormat = {Alignment = StringAlignment.Center}
      };
      Graph.EdgeDefaults.Labels.LayoutParameter = bezierPathLabelModel.CreateDefaultParameter();
    }

    private void SetupGraphML() {
      //Always use shared references for the sample graphs
      GraphControl.GraphMLIOHandler.ResolveReference += delegate(object sender, ResolveReferenceEventArgs args) {
        switch (args.ReferenceId) {
          case "bezierPathLabelModel":
            args.Value = bezierPathLabelModel;
            break;
          case "bezierSegmentLabelModel":
            args.Value = bezierEdgeSegmentLabelModel;
            break;
          default:
            break;
        }
      };
    }

    private void RegisterBezierDecorators() {
      Graph.GetDecorator().BendDecorator.HandleDecorator.HideImplementation(
          b => !EnableEditing && b.Owner.Style is yWorks.Graph.Styles.BezierEdgeStyle && b.Owner.Bends.Count % 3 == 2);

      Graph.GetDecorator().BendDecorator.HandleDecorator.SetImplementationWrapper(
          b => EnableEditing && SmoothEditing && b.Owner.Style is yWorks.Graph.Styles.BezierEdgeStyle && b.Owner.Bends.Count % 3 == 2,
          delegate(IBend b, IHandle h) {
            var index = b.GetIndex();
            switch (index % 3) {
              case 0:
              case 1:
                //Handle for the first control point of a triple
                return new OuterControlPointHandle(h, b);
              case 2:
              default:
                //The "middle" control point controls the previous and next ones
                return new InnerControlPointHandle(h, b);
            }
          });

      //Override the default for bezier edges
      Graph.GetDecorator().EdgeDecorator.BendCreatorDecorator.SetImplementation(
          edge => EnableEditing && edge.Style is yWorks.Graph.Styles.BezierEdgeStyle,
          new BezierBendCreator());

      //And always show bend handles
      Graph.GetDecorator().EdgeDecorator.HandleProviderDecorator.SetImplementationWrapper(edge => EnableEditing && edge.Style is yWorks.Graph.Styles.BezierEdgeStyle,
          (edge, coreImpl) => new BezierEdgeHandleProvider(edge, coreImpl));

      Graph.GetDecorator().EdgeDecorator.SelectionDecorator.SetImplementationWrapper(e => e.Style is yWorks.Graph.Styles.BezierEdgeStyle,
          (e, coreImpl) => new BezierSelectionIndicatorInstaller(coreImpl));
    }


    private void RequeryHandles() {
      if (graphControl.InputMode != null) {
        ((GraphEditorInputMode) graphControl.InputMode).RequeryHandles();
      }
    }

    private static readonly yWorks.Graph.Styles.BezierEdgeStyle bezierEdgeStyle =
        new yWorks.Graph.Styles.BezierEdgeStyle {
            Pen = new Pen(new SolidBrush(Color.FromArgb(0x41, 0x69, 0xe1)), 3),
            TargetArrow = new Arrow(Color.FromArgb(0x41, 0x69, 0xe1)) { Type = ArrowType.Triangle, Pen = { LineJoin = LineJoin.Miter, MiterLimit = 10 } }
        };

    private bool smoothEditing;
    private readonly BezierEdgeSegmentLabelModel bezierEdgeSegmentLabelModel;
    private readonly BezierEdgePathLabelModel bezierPathLabelModel;
    private bool autoRotation;
    private double angle;
    private bool autoSnapping;
    private bool enableEditing;

    public bool SmoothEditing {
      get { return smoothEditing; }
      set {
        smoothEditing = value;
        if (GraphControl != null) {
          var geim = GraphControl.InputMode as GraphEditorInputMode;
          if (geim != null) {
            var bceim = geim.CreateEdgeInputMode as BezierCreateEdgeInputMode;
            if (bceim != null) {
              bceim.CreateSmoothSplines = value;
            }
            geim.RequeryHandles();
          }
        }
      }
    }

    /// <summary>
    /// Returns the GraphControl instance used in the form.
    /// </summary>
    public GraphControl GraphControl {
      get { return graphControl; }
    }

    /// <summary>
    /// Gets the currently registered IGraph instance from the GraphControl.
    /// </summary>
    public IGraph Graph {
      get { return GraphControl.Graph; }
    }

    public bool AutoRotation {
      get { return autoRotation; }
      set {
        if (autoRotation != value) {
          autoRotation = value;
          bezierEdgeSegmentLabelModel.AutoRotation = value;
          bezierPathLabelModel.AutoRotation = value;
          if (GraphControl != null) {
            GraphControl.Invalidate();
          }
        }
      }
    }

    public bool AutoSnapping {
      get { return autoSnapping; }
      set {
        if (autoSnapping != value) {
          autoSnapping = value;
          bezierEdgeSegmentLabelModel.AutoSnapping = value;
          bezierPathLabelModel.AutoSnapping = value;
          if (GraphControl != null) {
            GraphControl.Invalidate();
          }
        }
      }
    }
    public double Angle {
      get { return angle; }
      set {
        if (angle != value) {
          angle = value;
          bezierEdgeSegmentLabelModel.Angle = Math.PI * angle / 180.0;
          bezierPathLabelModel.Angle = Math.PI * angle / 180.0;
          if (GraphControl != null) {
            GraphControl.Invalidate();
          }
        }
      }
    }

    public bool EnableEditing {
      get { return enableEditing; }
      set {
        if (enableEditing != value) {
          enableEditing = value;
          if (GraphControl != null) {
            var geim = GraphControl.InputMode as GraphEditorInputMode;
            if (geim != null) {
              geim.RequeryHandles();
            }
          }
        }
      }
    }

    private void exitToolStripMenuItem_Click(object sender, EventArgs e) {
      Application.Exit();
    }

    private void newButton_Click(object sender, EventArgs e) {
      graphControl.Graph.Clear();
    }

    private void newToolStripMenuItem_Click(object sender, EventArgs e) {
      graphControl.Graph.Clear();
    }

    private void SampleChanged(object sender, EventArgs e) {
      if (GraphControl != null) {
        switch (sampleComboBox.SelectedItem) {
          case "Circular Layout":
            GraphControl.ImportFromGraphML("Resources\\SampleCircle.graphml");
            break;
          case "Graph with Labels":
            GraphControl.ImportFromGraphML("Resources\\SampleLabels.graphml");
            break;
        }
      }
    }

    private void EnableEditButtonClick(object sender, EventArgs e) {
      EnableEditing = editingButton.Checked;
    }

    private void SmoothEditingButtonClick(object sender, EventArgs e) {
      SmoothEditing = smoothEditingButton.Checked;
    }

    private void AutoRotationButtonClick(object sender, EventArgs e) {
      AutoRotation = autoRotationButton.Checked;
    }

    private void AutoSnappingButtonClick(object sender, EventArgs e) {
      AutoSnapping = autoSnappingButton.Checked;
    }

    private void AngleTextChanged(object sender, EventArgs e) {
      double resultDouble;
      if (double.TryParse(angleTextBox.Text, out resultDouble)) {
        Angle = resultDouble;
      }
    }

    #region Main

    /// <summary>
    /// The main entry point for the application.
    /// </summary>
    [STAThread]
    private static void Main() {
      Application.EnableVisualStyles();
      Application.SetCompatibleTextRenderingDefault(false);
      Application.Run(new BezierEdgeStyleForm());
    }

    #endregion
  }
}
