/****************************************************************************
 ** 
 ** This demo file is part of yFiles.NET 5.6.
 ** Copyright (c) 2000-2024 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 ** 
 ** yFiles demo files exhibit yFiles.NET functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 ** 
 ** Owners of a valid software license for a yFiles.NET version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles.NET powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles.NET
 ** license agreement.
 ** 
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ** 
 ***************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.yFiles.ImageExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageExport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageExport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.yFiles.ImageExport.ImageExport", typeof(ImageExport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Export.
        /// </summary>
        internal static string IMAGE_EXPORT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_CONTENT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Content.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_CONTENT_VALUE_FIT_CONTENT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.CONTENT.VALUE.FIT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Visible Region.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_CONTENT_VALUE_VIEWPORT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.CONTENT.VALUE.VIEWPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_HEIGHT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_SCALE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_SIZE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Height.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_SIZE_VALUE_SPECIFY_HEIGHT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.SIZE.VALUE.SPECIFY_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Width.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_SIZE_VALUE_SPECIFY_WIDTH {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.SIZE.VALUE.SPECIFY_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Original Size.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_SIZE_VALUE_USE_ORIGINAL_SIZE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.SIZE.VALUE.USE_ORIGINAL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_WIDTH {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string IMAGE_EXPORT_BOUNDS_ZOOM {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.BOUNDS.ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMF.
        /// </summary>
        internal static string IMAGE_EXPORT_EMF {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.EMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string IMAGE_EXPORT_EMF_TRANSPARENT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.EMF.TRANSPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Options.
        /// </summary>
        internal static string IMAGE_EXPORT_GRAPHICS {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.GRAPHICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Interpolation Mode.
        /// </summary>
        internal static string IMAGE_EXPORT_GRAPHICS_INTERPOLATION {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.GRAPHICS.INTERPOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Offset Mode.
        /// </summary>
        internal static string IMAGE_EXPORT_GRAPHICS_PIXELOFFSET {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.GRAPHICS.PIXELOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing Mode.
        /// </summary>
        internal static string IMAGE_EXPORT_GRAPHICS_SMOOTHING {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.GRAPHICS.SMOOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Rendering Hint.
        /// </summary>
        internal static string IMAGE_EXPORT_GRAPHICS_TEXTRENDERING {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.GRAPHICS.TEXTRENDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG.
        /// </summary>
        internal static string IMAGE_EXPORT_JPG {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string IMAGE_EXPORT_JPG_QUALITY {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.JPG.QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string IMAGE_EXPORT_MARGINS {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.MARGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Margin.
        /// </summary>
        internal static string IMAGE_EXPORT_MARGINS_BOTTOM_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.MARGINS.BOTTOM_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin.
        /// </summary>
        internal static string IMAGE_EXPORT_MARGINS_LEFT_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.MARGINS.LEFT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Margin.
        /// </summary>
        internal static string IMAGE_EXPORT_MARGINS_RIGHT_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.MARGINS.RIGHT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin.
        /// </summary>
        internal static string IMAGE_EXPORT_MARGINS_TOP_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.MARGINS.TOP_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Rectangle Contents.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_EXPORT_RECTANGLE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.EXPORT_RECTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FILENAME {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_BMP {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMF.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_EMF {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_EMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_GIF {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_JPG {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_PNG {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_FORMAT_VALUE_FORMAT_TIFF {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.FORMAT.VALUE.FORMAT_TIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Decorations.
        /// </summary>
        internal static string IMAGE_EXPORT_OUTPUT_HIDE_DECORATIONS {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.OUTPUT.HIDE_DECORATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        internal static string IMAGE_EXPORT_PNG {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string IMAGE_EXPORT_PNG_TRANSPARENT {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.PNG.TRANSPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Depth.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Bit per Pixel.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH_VALUE_1 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH.VALUE.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Bits per Pixel.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH_VALUE_24 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH.VALUE.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Bits per Pixel.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH_VALUE_32 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH.VALUE.32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Bits per Pixel.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH_VALUE_4 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH.VALUE.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Bits per Pixel.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COLOR_DEPTH_VALUE_8 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COLOR_DEPTH.VALUE.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT3.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION_VALUE_COMPRESSION_CCITT3 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION.VALUE.COMPRESSION_CCITT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT4.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION_VALUE_COMPRESSION_CCITT4 {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION.VALUE.COMPRESSION_CCITT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZW.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION_VALUE_COMPRESSION_LZW {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION.VALUE.COMPRESSION_LZW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION_VALUE_COMPRESSION_NONE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION.VALUE.COMPRESSION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLE.
        /// </summary>
        internal static string IMAGE_EXPORT_TIFF_COMPRESSION_VALUE_COMPRESSION_RLE {
            get {
                return ResourceManager.GetString("IMAGE_EXPORT.TIFF.COMPRESSION.VALUE.COMPRESSION_RLE", resourceCulture);
            }
        }
    }
}
