/****************************************************************************
 ** 
 ** This demo file is part of yFiles.NET 5.2.
 ** Copyright (c) 2000-2019 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 ** 
 ** yFiles demo files exhibit yFiles.NET functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 ** 
 ** Owners of a valid software license for a yFiles.NET version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles.NET powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles.NET
 ** license agreement.
 ** 
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ** 
 ***************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.yFiles.Layout.NodeLabeling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NodeLabeling {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NodeLabeling() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.yFiles.Layout.NodeLabeling.NodeLabeling", typeof(NodeLabeling).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Size.
        /// </summary>
        internal static string LABEL_SIZE {
            get {
                return ResourceManager.GetString("LABEL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Label Properties.
        /// </summary>
        internal static string NODE_LABEL_PROPERTIES {
            get {
                return ResourceManager.GetString("NODE_LABEL_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Labeling.
        /// </summary>
        internal static string NODE_LABELING {
            get {
                return ResourceManager.GetString("NODE_LABELING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Model.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_EXTERIOR {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_EXTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_FREE {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Node.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_FREENODE {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_FREENODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_INTERIOR {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_INTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Stretch.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_INTERIORSTRETCH {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_INTERIORSTRETCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandwich.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_SANDWICH {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_SANDWICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Distances.
        /// </summary>
        internal static string NODE_LABELING_LABEL_MODEL_VALUE_LABEL_MODEL_THREE_DISTANCE {
            get {
                return ResourceManager.GetString("NODE_LABELING.LABEL_MODEL.VALUE.LABEL_MODEL_THREE_DISTANCE", resourceCulture);
            }
        }
    }
}
